# -*- coding: utf-8 -*-
"""PPT_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwARXfNPQLlBG9Mb23pI_eu_T1UkeFYh
"""

!pip install google-generativeai python-pptx Pillow requests python-dotenv

import os
import google.generativeai as genai
from dotenv import load_dotenv
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from PIL import Image
import requests
import io
import json

load_dotenv()

import os
import json
import requests
from pptx import Presentation
from pptx.util import Pt, Inches
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import google.generativeai as genai


class PPTgenerator:
    def __init__(self, api_key=None):
        self.api_key = api_key
        if not self.api_key:
            raise ValueError("Gemini API is not there..")

        genai.configure(api_key=self.api_key)
        self.model = genai.GenerativeModel('gemini-2.5-pro')
        self.model_vision = genai.GenerativeModel('gemini-2.5-pro')

        self.presentation = Presentation()

    def generate_content_outline(self, topic, num_slides=7):
        """Generate content outline for a given topic using Gemini..."""
        prompt = f"""
        Create a detailed outline for PowerPoint presentation on topic "{topic}" with "{num_slides}" slides.
            [
              {{
                "title":"Slide Title",
                "content":"Main content points as bullet points",
                "slide_type":"title|content|image|conclusion"
              }}
            ]

        Make sure the content is engaging, informative and well-structured.
        The response must be a valid JSON array.
        """
        try:
            response = self.model.generate_content(prompt)

            # Extract text safely
            if hasattr(response, "text"):
                content = response.text
            elif hasattr(response, "candidates"):
                # Gemini sometimes returns structured candidates
                content = response.candidates[0].content.parts[0].text
            else:
                # Fallback — handle any direct list or dict
                content = str(response)

            # Ensure it's a string
            if isinstance(content, list):
                content = " ".join(map(str, content))
            elif isinstance(content, dict):
                content = json.dumps(content)

            content = content.strip()

            # Clean up markdown fences if they exist
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].strip()

            # Try parsing as JSON
            if content.startswith('[') and content.endswith(']'):
                try:
                    return json.loads(content)
                except json.JSONDecodeError:
                    print("JSON decoding failed. Returning raw text.")
                    return None
            else:
                print("Content not in JSON array format.")
                return None

        except Exception as e:
            print(f"Error in generate_content_outline: {e}")
            return None

    def generate_image_description(self, slide_content):
        prompt = f"""
        Based on this slide content, suggest a relevant image description that
        would enhance the presentation. {slide_content}
        Return only a brief, descriptive phrase suitable for image search (max 5 words)
        """
        try:
            response = self.model.generate_content(prompt)

            # Safely extract text
            if hasattr(response, "text"):
                content = response.text
            elif hasattr(response, "candidates"):
                content = response.candidates[0].content.parts[0].text
            else:
                content = str(response)

            # Convert list or dict safely
            if isinstance(content, list):
                content = " ".join(map(str, content))
            elif isinstance(content, dict):
                content = json.dumps(content)

            # Ensure it's a string
            content = str(content).strip()

            # Remove markdown code fences if present
            if "```" in content:
                content = content.replace("```json", "").replace("```", "").strip()

            # Sometimes Gemini returns multiple lines — pick the first few words
            content = content.split("\n")[0].split(".")[0][:50]

            return content or "Professional Presentation"

        except Exception as e:
            print(f"Error in generate_image_description: {e}")
            return "Professional Presentation"


    def download_image(self, query, save_path="temp_image.jpg"):
        try:
            url = "https://api.pexels.com/v1/search"
            headers = {
                "Authorization": "ScmwB0T49kK2B1CdBQZRMokd01uo8PmKRMMDJx7tSOxbCRvZ52RGj6ip"
            }

            params = {
                "query": query,
                "per_page": 1,
                "orientation": "landscape"
            }

            response = requests.get(url, headers=headers, params=params)
            response.raise_for_status()

            data = response.json()
            if not data.get('photos'):
                raise ValueError("No photos found for the given query.")

            image_url = data['photos'][0]['src']['original']
            image_response = requests.get(image_url)
            image_response.raise_for_status()

            with open(save_path, 'wb') as f:
                f.write(image_response.content)

            return save_path

        except Exception as e:
            print(e)
            return None

    def create_title_slide(self, title, subtitle=""):
        slide_layout = self.presentation.slide_layouts[0]
        slide = self.presentation.slides.add_slide(slide_layout)

        title_shape = slide.shapes.title
        title_shape.text = title
        title_shape.text_frame.paragraphs[0].font.size = Pt(30)
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(0, 0, 0)
        title_shape.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER

        if subtitle:
            subtitle_shape = slide.placeholders[1]
            subtitle_shape.text = subtitle
            subtitle_shape.text_frame.paragraphs[0].font.size = Pt(20)
            subtitle_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(0, 0, 0)
            subtitle_shape.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER

    def create_content_slide(self, title, content, include_image=False):
        slide_layout = self.presentation.slide_layouts[1]
        slide = self.presentation.slides.add_slide(slide_layout)

        title_shape = slide.shapes.title
        title_shape.text = title
        title_shape.text_frame.paragraphs[0].font.size = Pt(30)
        title_shape.text_frame.paragraphs[0].font.bold = True

        content_shape = slide.placeholders[1]
        content_shape.text = content
        for paragraph in content_shape.text_frame.paragraphs:
            paragraph.font.color.rgb = RGBColor(0, 0, 0)
            paragraph.font.size = Pt(20)

        if include_image:
            try:
                image_desc = self.generate_image_description(content)
                image_path = self.download_image(image_desc)
                if image_path and os.path.exists(image_path):
                    slide.shapes.add_picture(image_path, Inches(6), Inches(2), height=Inches(4))
                    os.remove(image_path)
            except Exception as e:
                print(e)

        return slide

    def create_image_slide(self, title, content, image_query):
        slide_layout = self.presentation.slide_layouts[1]
        slide = self.presentation.slides.add_slide(slide_layout)

        title_box = slide.shapes.add_textbox(Inches(1), Inches(1), Inches(8), Inches(1))
        title_frame = title_box.text_frame
        title_frame.text = title
        title_frame.paragraphs[0].font.size = Pt(30)
        title_frame.paragraphs[0].font.bold = True
        title_frame.paragraphs[0].font.color.rgb = RGBColor(0, 0, 0)
        title_frame.paragraphs[0].alignment = PP_ALIGN.CENTER

        content_box = slide.shapes.add_textbox(Inches(0.5), Inches(2), Inches(4), Inches(5))
        content_frame = content_box.text_frame
        content_frame.text = content
        for paragraph in content_frame.paragraphs:
            paragraph.font.size = Pt(20)
            paragraph.font.color.rgb = RGBColor(255, 0, 255)

        try:
            image_path = self.download_image(image_query)
            if image_path and os.path.exists(image_path):
                slide.shapes.add_picture(image_path, Inches(6), Inches(2), height=Inches(4))
                os.remove(image_path)
        except Exception as e:
            print(e)

        return slide

    def generate_presentation(self, topic, num_slides=7, output_file="presentation.pptx"):
        content_outline = self.generate_content_outline(topic, num_slides)
        if not content_outline:
            print("Failed to generate content outline.")
            return None

        for i, slide_data in enumerate(content_outline):
            title = slide_data["title"]
            content = slide_data["content"]
            slide_type = slide_data["slide_type"]

            print(f"Creating slide {i + 1}: {title}")

            if i == 0 or slide_type == "title":
                self.create_title_slide(title, "Created By Nishant")
            elif slide_type == "image":
                image_query = self.generate_image_description(content)
                self.create_image_slide(title, content, image_query)
            else:
                include_image = (i % 3 == 0)
                self.create_content_slide(title, content, include_image)

        self.presentation.save(output_file)
        print(f"Presentation saved to {output_file}")
        return output_file


print("Generation initialised......")

api_key = "AIzaSyAAuW9fbMd46gXHNtb5rci9SBZuvMXuKgM"

try:
  generator = PPTgenerator(api_key=api_key)
except ValueError as e:
  print(e)

#Generation of PPT
topic = "Artificial intelligence in agriculture"
num_slides = 7

try:
  output_file = generator.generate_presentation(topic, num_slides, "ai_agriculture_presentation.pptx")
except Exception as e:
  print(e)

